# Generated by Django 3.1.7 on 2021-07-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arsip', '0003_surat_keputusan'),
    ]

    operations = [
        migrations.CreateModel(
            name='sop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_arsip', models.CharField(blank=True, max_length=100, null=True)),
                ('dokumen', models.CharField(blank=True, max_length=100, null=True)),
                ('bulan', models.CharField(blank=True, choices=[('januari', 'januari'), ('februari', 'februari'), ('maret', 'maret'), ('april', 'april'), ('mei', 'mei'), ('juni', 'juni'), ('juli', 'juli'), ('agustus', 'agustus'), ('september', 'september'), ('oktober', 'oktober'), ('november', 'november'), ('desember', 'desember')], max_length=20, null=True)),
                ('tanggal', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sop',
            },
        ),
    ]
