# Generated by Django 3.1.2 on 2021-08-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arsip', '0004_sop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lpm',
            name='dokumen',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
