# Generated by Django 3.1.2 on 2021-08-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arsip', '0005_auto_20210807_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedoman',
            name='dokumen',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
