# Generated by Django 3.1.2 on 2021-08-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arsip', '0007_auto_20210807_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surat_keputusan',
            name='dokumen',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
